adding bsd-3 clause license
atoum/stubs pull request #15
Opened 2016-09-28 10:01 UTC by marcomenzel

referring to #13

2016-09-28 10:10 UTC, jubianchi requested changes

2016-09-28 10:10 UTC, jubianchi commented on README.md
> +atoum stubs is released under the BSD-3-Clause License. See the bundled LICENSE file for details.
`s/is/are/`

2016-09-28 10:14 UTC, marcomenzel commented
ouch :-1:  should be fine now.

2016-09-28 10:18 UTC, jubianchi approved these changes

2016-09-28 20:33 UTC, tarlepp commented
Hmm you guys realize that is not october yet :D

2016-09-28 20:37 UTC, marcomenzel commented
Just getting things done which no one cares about the whole year..

2016-09-28 21:14 UTC, jubianchi commented
@tarlepp any contribution is always good. And we welcome everyone.

Yes, it's not October yet but I'll open a lot more issue for the Hacktoberfest ;)

@marcomenzel if you wish to make this PR count for your score, just close it and we'll reopen it in a few days ;)

2016-10-02 15:31 UTC, jubianchi commented
@marcomenzel thanks!

2016-10-02 15:31 UTC, merged